export const MAX_FIRST_NAME_LENGTH = 100;
export const MAX_LAST_NAME_LENGTH = 100;
export const MIN_PASSWORD_LENGTH = 8;
export const MAX_PASSWORD_LENGTH = 100;
export const MIN_USERNAME_LENGTH = 8;
export const MAX_USERNAME_LENGTH = 50;
export const MAX_TICKET_DESCRIPTION_LENGTH = 1000;